import Footer from "@/components/footer";
import Navbar from "@/components/navbar";
import { AuthProvider } from "@/contexts/AuthContext";
import { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const links = [
  { href: "/", label: "Home" },
  { href: "/about", label: "About Me" },
  { href: "/contact", label: "Contact" },
  { href: "/projects", label: "Projects" },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${rubik.className} bg-whisper rounded-xl px-5 py-3`}>
        <AuthProvider>
          <Navbar links={links} />
          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
